services:
  ros:
#    image: ros:jazzy
    build:
      context: .
      dockerfile: DockerFile
    #image: osrf/ros:jazzy-desktop-full
    user: 1000:1000
    container_name: ros_jazzy
    environment:
      WAYLAND_DISPLAY: wayland-1
      QT_QPA_PLATFORM: wayland
      XDG_RUNTIME_DIR: /tmp/xdg
    volumes:
      - ./:/workspace
      #wayland socket
      - /run/user/1000/:/tmp/xdg
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: bash
